#1. Array Creation Functions

In [1]:
import numpy as np

In [2]:
#Create an array from list
a = np.array([1,2,3])
print("Array a : ", a )

Array a :  [1 2 3]


In [3]:
#Create an array with evenly spaced values
b= np.arange(0,10,2) # Will have values from 0 to 9 with step count 2 
print("Array b : ",b)

Array b :  [0 2 4 6 8]


In [4]:
#Create an array with linearly spaced value
c = np.linspace(0,1,5) #5 values evenly spaced between 0 to 1
print("Array c : ",c )

Array c :  [0.   0.25 0.5  0.75 1.  ]


In [7]:
#Create a array filled with ones
c1=np.ones((3,2)) # prints 3 rows with 2 columns of 1s with data type float
print("Array c1 is : ",c1)

Array c1 is :  [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [6]:
#Create a array filled with ones
d=np.zeros((3,2)) # prints 3 rows with 2 columns of 0s with data type float
print("Array d is : ",d)

Array d is :  [[0. 0.]
 [0. 0.]
 [0. 0.]]


In [8]:
#Create an Identity matrix
f= np.eye(4) # gives 4x4 matrix that means diagonally it will have the same value. 
print("Identity Matrix f:\n",f)

Identity Matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 2. Array Manipulation Functions

In [9]:
#Reshape an Array
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(1,3)) # Reshapes to 1row x 3 column. Since its a 1d, it would only reshape accordingy
print("Reshaped array of",a1,"is\n : ",reshaped)

Reshaped array of [1 2 3] is
 :  [[1 2 3]]


In [10]:
#Flatten an Array
f1= np.array([[1,2],[3,4]])
flattened = np.ravel(f1) # Flatten to 1D Array
print("Flattened array: ", flattened)

Flattened array:  [1 2 3 4]


In [11]:
#Transpose an array 
e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1) # Transpose the arra
print("Transposed array is : ", transposed)

Transposed array is :  [[1 3]
 [2 4]]


In [13]:
#Stack arrays vertically 
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.vstack([a2,b2])#Stack a and b vertically 
print("Stacked arrays : \n", stacked)

Stacked arrays : 
 [[1 2]
 [3 4]]


#3.Mathematical Functions

In [14]:
#Add two arrays
g = np.array([1,2,3,4])
addfun = np.add(g,2) #adds 2 to each element in array
print("Added 2 to g : ",addfun)

Added 2 to g :  [3 4 5 6]


In [29]:
#Square each element in array
g = np.array([1,2,3,4])
squared = np.power(g,2) #Squares each element
print("The squared array is ", squared)

The squared array is  [ 1  4  9 16]


In [30]:
#Square root of each element
sqrt_val = np.sqrt(g)#Square root of g
print("sqaure root is : ",sqrt_val)

sqaure root is :  [1.         1.41421356 1.73205081 2.        ]


In [23]:
a1


array([1, 2, 3])

In [24]:
g

[1, 4, 9, 16]

In [31]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4]


In [32]:
#Dot product of two arrays
a2 = np.array([1,2,3])

In [33]:
dot_product = np.dot(a2,g) #Dot product is inner product of vector
print("Dot product of ",a2,"and ",g, ":",dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [34]:
print(a)

[1 2 3]


In [35]:
print(a1)

[1 2 3]


In [37]:
a3 == np.array([1, 2, 3])
dot_product = np.dot(a1, a)  # Dot product of a and g
print("Dot product of a1 and a:", dot_product)

Dot product of a1 and a: 14
